# engines:
  # duplication:
    # enabled: true
    # config:
      # languages:
      # - javascript
    # checks:
      # Similar code:
        # enabled: false
exclude_paths:
- node_modules/
- sample/
- test/