engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - lib/**
exclude_paths:
- node_modules/
- sample/
- test/